language: java

os: linux

sudo: required

services:
  - docker

before_install:
  - echo "This is before install"

install: skip

script:
  - gradlew check
  - docker image build -t bhargodevarya/repo:eureka-from-travis ./EurekaServer
  - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PWD
  - docker image push bhargodevarya/repo:eureka-from-travis
  - docker logout


after_script:
  - echo "Script is finished"

after_success:
  - echo "after success"