language: java

os: linux

sudo: required

services:
  - docker

branches:
  only:
    - master
    - /feature*/

before_install:
  - echo "This is before install"

install: skip

script:
  - bash test.sh $DOCKER_HUB_ID $DOCKER_HUB_PWD


after_script:
  - echo "Script is finished"

after_success:
  - echo "after success"