eureka:
  instance:
   homePageUrlPath: http://localhost:9090/user/setup
   appName: userservice
   hostName: localhost
   statusPageUrlPath: http://localhost:9090/user/setup

server:
  port: 9090

spring:
  application:
    name: userservice