eureka:
  instance:
   homePageUrlPath: http://localhost:9090/user/setup
   appName: userservice
   hostName: localhost
   statusPageUrlPath: http://localhost:9090/user/setup
  client:
   serviceUrl:
    # url for the eureka server
    defaultZone: http://localhost:8300/eureka


server:
  port: 9090

spring:
  application:
    name: userservice